version: '3.8'
services:
  sqmusic_main:
    image: registry.cn-hangzhou.aliyuncs.com/sqdockler/simple_sq_music_plus:latest
    container_name: sqmusic_main
    environment:
      - DB_IP=mysql
      - DB_PORT=3306
      - DB_NAME=sqmusicv3
      - DB_USERNAME=root
      - DB_PASSWORD=sqmusicv3password
    volumes:
      - ./music:/music
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sq-app-network
    expose:
      - "8099"
    restart: always

  sqmusic_web:
    image: registry.cn-hangzhou.aliyuncs.com/sqdockler/simple_sq_music_plus_web:latest
    container_name: sqmusic_web
    ports:
      - "8097:80"
    networks:
      - sq-app-network
    depends_on:
      - sqmusic_main
    restart: always

  mysql:
    image: mysql:5.7
    container_name: sqmusic_mysql
    environment:
      MYSQL_ROOT_PASSWORD: sqmusicv3password
      MYSQL_DATABASE: sqmusicv3
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - sq-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  sq-app-network:
    driver: bridge
